services:
  # Service Backend (FastAPI)
  - type: web
    name: powercee-backend
    env: python
    region: frankfurt  # ou oregon, selon ton choix
    rootDir: back      # <--- C'est ICI que la magie du monorepo opère
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false # On devra la mettre manuellement dans le dashboard Render pour la sécurité
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 # Nombre de workers Uvicorn

databases:
  # On n'en met pas car on utilise Neon externe